apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: hello-devops
        image: hello-devops:1.0
        ports:
        - containerPort: 3000
